package com.hackzurich.ws03.app08;

public class Constants {
    public static String PREF_CONSTANT_SETTINGS_NAME= "PREF_CONSTANT_NAME";

    public static String PREF_CONSTANT_SETTINGS_PATIENT_ID = "PREF_CONSTANT_SETTINGS_PATIENT_ID";
    public static String DEVICE_ADDRESS_EXTRA = "device.address";

    public static String PREF_CONSTANT_PATRONUS_TODAY= "PREF_CONSTANT_PATRONUS_TODAY";
    public static String PREF_CONSTANT_PATRONUS_AVERAGE= "PREF_CONSTANT_PATRONUS_AVERAGE";
    public static String PREF_CONSTANT_PATRONUS= "PREF_CONSTANT_PATRONUS"; // TOTAL

    public static String PREF_CONSTANT_PATRONUS_STEPS = "PREF_CONSTANT_PATRONUS_STEPS";
    public static String PREF_CONSTANT_PATRONUS_STEPS_POINTS = "PREF_CONSTANT_PATRONUS_STEPS_POINTS";

    public static String PREF_CONSTANT_PATRONUS_EXPLORATION_POINTS = "PREF_CONSTANT_PATRONUS_EXPLORATION_POINTS";

    public static String PREF_CONSTANT_PATRONUS_BREATHING_DETECTED = "PREF_CONSTANT_PATRONUS_EXPLORATION_POINTS";
    public static String PREF_CONSTANT_PATRONUS_BREATHING_POINTS = "PREF_CONSTANT_PATRONUS_EXPLORATION_POINTS";


}
